[build]
publish = "public"
command = "npm ci && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.production.environment]
HUGO_VERSION = "0.121.0"
HUGO_ENV = "production"
NODE_VERSION = "18.20.0"
NPM_VERSION = "10.5.0"

[context.deploy-preview]
command = "npm ci && hugo --gc --minify --buildDrafts --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.121.0"
HUGO_ENABLEGITINFO = "true"
NODE_VERSION = "18.20.0"
NPM_VERSION = "10.5.0"

[context.branch-deploy]
command = "npm ci && hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.121.0"
HUGO_ENABLEGITINFO = "true"
NODE_VERSION = "18.20.0"
NPM_VERSION = "10.5.0"
